In [3]:
#How numpy is efficient than normal function in python
import numpy as np

L = range(1000)

%timeit [i**2 for i in L]


A = np.arange(1000)

%timeit A**2


226 µs ± 16.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.18 µs ± 40.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
# How to create a array using list in python
B = np.array([1,2,3,4])
B
B.ndim
B.shape
len(B)
#len is return the first attribute of the shape.
# 1d array is known as vector.
# .2d array is known as matrix.
# and multidimensional array is known as tensor .



4

In [12]:
# 1. using arange() function it's required three agr. i-> start,ii->end,iii->step.(ii is comp.)
B = np.arange(10)
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
B = np.arange(1,10,3)
B

array([1, 4, 7])

In [18]:
B = np.arange(10,1,-3)
B


array([10,  7,  4])

In [20]:
B = np.ones((2,3),dtype=int) # it's required a tuple
B

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
B = np.zeros((3,),dtype=float)
B

array([0., 0., 0.])

In [26]:
B = np.eye(4,2)
B

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [27]:
B = np.diag([1,2,3,5])
B

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 5]])

In [33]:
B = np.diag(B)
B

array([1, 2, 3, 5])

In [34]:
B = np.random.rand(4)
B

array([0.48343519, 0.42197969, 0.93968275, 0.16470924])

In [35]:
B=np.random.randn(4)
B

array([-0.43277004,  0.16631337,  0.54286149, -0.04302521])

In [36]:
# indexing and slicing in python numpy array.
B[3]

-0.04302521040377797

In [37]:
B = np.arange(10)
B[5:]=10
B

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [40]:
B = np.arange(10)
C = np.arange(5)
B[5:]=C[::-1]
B

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [41]:
# Views and copy in numpy.
A = np.arange(10)
B = A[::2]
np.shares_memory(A,B)

True

In [42]:
# A and B are share the same memory their are making a shallow copy.
# if we want to make the copy we need to use the copy function.
B[0]=10
print(A)
print(B)
# here i just modified B but it's modified A also.

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [43]:
A = np.arange(10)
B = A[::2].copy()
print(A)
print(B)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [44]:
A[0] = 5
print(A)
print(B)

[5 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [48]:
# Fancy indexing.
# 1. Mask
A = np.random.randint(0,20,15)
A



array([ 8,  6, 17,  5, 11, 14,  7, 15, 15,  9,  4, 10, 12,  6,  2])

In [50]:
mask = (A%2==0) 
# What is does is it's take all the element of the array A and then 
# check for every element of array which are satisfied the condition
# Ai%2==0 and store the index of it in the mask
A[mask]
print(mask.dtype)
print(mask)
print(A[mask])

bool
[ True  True False False False  True False False False False  True  True
  True  True  True]
[ 8  6 14  4 10 12  6  2]


In [51]:
mask = [1,2,3,5]
A[mask]

array([ 6, 17,  5, 14])

In [52]:
A[[2,3,4,9,2]]

array([17,  5, 11,  9, 17])

In [53]:
# Operation on numpy arrays

A = np.array([1,2,3,4])
# adding a scalar number to it
A + 1

array([2, 3, 4, 5])

In [58]:
# Vector addition.
A+[1,2,3,4]

array([2, 4, 6, 8])

In [59]:
# Multiplication.
A**2

array([ 1,  4,  9, 16])

In [61]:
#Matrix multiplication.
A = np.diag([1,2,3,4])
B = np.diag([2,3,4,5])
print(A*B)
print("*************")
print(A.dot(B))

[[ 2  0  0  0]
 [ 0  6  0  0]
 [ 0  0 12  0]
 [ 0  0  0 20]]
*************
[[ 2  0  0  0]
 [ 0  6  0  0]
 [ 0  0 12  0]
 [ 0  0  0 20]]


In [66]:
# Compare every element of the array.
A = [2,4,6,7,8]
B = [2,3,5,7,2]
print(A==B)
print(A>B)

False
True


In [65]:
# now take declare as the np array
A = np.array(A)
B = np.array(B)
print(A==B)
print(A>B)

[ True False False  True False]
[False  True  True False  True]


In [70]:
# what if you actually want to compare if array is equal or not
np.array_equal(A,B)
print(np.array_equal(A,B))

False


In [3]:
# Logical operation
import numpy as np
A = np.array([1,0,1,0],dtype=bool)
B = np.array([0,1,0,0],dtype=bool)
np.logical_or(A,B)

array([ True,  True,  True, False])

In [4]:
# Mathematical operation
np.sin(A)


array([0.8413, 0.    , 0.8413, 0.    ], dtype=float16)

In [5]:
np.log(A)

/home/ashutosh/PycharmProjects/python/venv/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([  0., -inf,   0., -inf], dtype=float16)

In [7]:
# Reduction
np.sum(A)

2

In [8]:
A = [[1,2,3],[4,5,6]]
np.sum(A)

21

In [6]:
import numpy as np
A = [[1,1,3],[4,5,6]]
A = np.array(A)
print(A.sum())
print(A.sum(axis = 0))
print(A.sum(axis = 1))
print(A.min())
print(A.max())
print(A.argmin())
print(A.argmax())
# sum will return total sum of all element.
# sum(axis = 0 ) will return sum of each column.
# sum(axis = 1) will return sum of each row.

20
[5 6 9]
[ 5 15]
1
6
0
5


In [10]:
# Logical operation like all and any
A = np.array([True,False,True],dtype = bool)
print(A.any())
print(A.all())

True
False


In [16]:
# Statical operations
A = np.random.randint(1,20,14)
print(A)
print(A.mean())
print(np.median(A))
print(np.std(A))

[15  3 10  6  9  1  8 10  9 14 19  4  7 19]
9.571428571428571
9.0
5.3280160568490045


In [17]:
# Working with data in numpy
data = np.loadtxt("populations.txt")
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [18]:
year , hear , lynx , carrot = data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [23]:
populations = data[:,1:]
print(populations)

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]


In [25]:
np.std(data,axis=0)


array([6.05530071e+00, 2.08979065e+04, 1.62545915e+04, 3.32250623e+03])

In [26]:
np.median(data,axis = 0)

array([ 1910., 25400., 12300., 41800.])

In [31]:
# For each year which species ths maximum population
print(np.max(data[:,1:4],axis=1))
print(np.argmax(data[:,1:4],axis = 1))


[48300. 48200. 70200. 77400. 59400. 41700. 38600. 42300. 44500. 42100.
 46000. 46800. 57000. 76600. 52300. 51100. 36700. 41800. 43300. 41300.
 47300.]
[2 2 0 0 1 1 2 2 2 2 2 2 0 0 0 1 2 2 2 2 2]


In [36]:
# Broadcasting in numpy
# Just simple addition
A = np.ones((4,3),dtype=int)
print(A)
B = np.ones((4,3),dtype=int)
print(B)
print(A+B)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [47]:
A = np.tile(np.arange(1,10,3),(1,1))
print(A)
B = np.tile(np.arange(3,10,3),(3,1))
print(B)

[[1 4 7]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


In [52]:
print(A+B)
A = np.arange(1,10,3)
# Convert 1d array into 2d array by using special function.
A = A[:,np.newaxis]
print(A)
print(A+B)
B = np.arange(3,10,3)
print(B)
print(A)
print(A+B)



[[ 4  7 10]
 [ 7 10 13]
 [10 13 16]]
[[1]
 [4]
 [7]]
[[ 4  7 10]
 [ 7 10 13]
 [10 13 16]]
[3 6 9]
[[1]
 [4]
 [7]]
[[ 4  7 10]
 [ 7 10 13]
 [10 13 16]]
